void *malloc_checked(unsigned int b);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *_calloc(unsigned int nmemb, unsigned int size);
int *array_range(int min, int max);
void *_realloc(void *ptr, unsigned int old_size, unsigned int new_size);
int main(int argc, char *argv[]);
void sum_of_nums(char *result, char *next_p, int n_len);
void find_product(char *product, char *result, int d, int z);
char *itrate_size(char *s);
int get_digits(char ch);
char *create_xarray(int size);
int comput_length(char *s);
